GET http://localhost:4000/api/contacts

###
GET http://localhost:4000/api/contacts/view/60a9250e4b2aac11cc99ced2

###

POST http://localhost:4000/api/contacts/create
Content-Type: application/json

{
  "name": "John Doe",
  "isCompany": "false",
  "email": "johndoe@gmail.com",
  "phone": ["0759 251 281", "0784 887 038"],
  "address": "222 New Magwegwe",
  "balance": "100"
}

###
post http://localhost:4000/api/contacts/edit/60a91ffa4b2aac11cc99ced1
Content-Type: application/json

{
  "isCompany": "company",
  "phone": ["0766562"],
  "name": "Rockweed pvt ltd ffff",
  "email": "test@gmail.com",
  "address": "1277 Main Drive",
  "balance": "200"
}

###
# Register User
post http://localhost:4000/api/users
Content-Type: application/json

{
  "name": "Brian Karadzangare",
  "role": "admin",
  "email": "karadz@gmail.com",
  "mobile": "0733 251 281, 0784 887 038",
  "password": "karadz123456",
  "passwordConfirmation": "karadz123456"
}

###
# Register User
post http://localhost:4000/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "role": "admin",
  "email": "jdoe@gmail.com",
  "mobile": "0733 251 281, 0784 887 038",
  "password": "karadz123456",
  "passwordConfirmation": "karadz123456"
}



###
# Get auth user
get http://localhost:4000/api/auth
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjBiMmEwZmE3YTljMTNiZDc1OTQyNjBjIn0sImlhdCI6MTYyMjMxOTM1NCwiZXhwIjoxNjIyMzE5NzE0fQ.nYHT0Z4d6E0EWSJw51aaKVG70ZNxRCq0HAgI3vJmtCk


###
# Login User
post http://localhost:4000/api/auth
Content-Type: application/json

{
  "email": "karadz@gmail.com",
  "password": "karadz123456"
}